# Generated by Django 6.0.3 on 2026-03-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
